version: "3"
services:

  usb-pipeline:
    image: usb-pipeline
    volumes: 
        - ./workspace:/workspace
        
    deploy:
      resources:
        limits: 
            cpus: '12'
            memory: 128G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
    tty: true
